In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("E:/Data Science/adult_new.csv")

In [3]:
data

age         workclass  fnlwgt     education  educational-num  \
0       28         Local-gov  336951    Assoc-acdm               12   
1       44           Private  160323  Some-college               10   
2       63  Self-emp-not-inc  104626   Prof-school               15   
3       65           Private  184454       HS-grad                9   
4       48           Private  279724       HS-grad                9   
...    ...               ...     ...           ...              ...   
27409   27           Private  257302    Assoc-acdm               12   
27410   40           Private  154374       HS-grad                9   
27411   58           Private  151910       HS-grad                9   
27412   22           Private  201490       HS-grad                9   
27413   52      Self-emp-inc  287927       HS-grad                9   

           marital-status         occupation relationship   race  gender  \
0      Married-civ-spouse    Protective-serv      Husband  White    Male   
1      Married-civ-spouse  Machine-op-inspct      Husband  Black    Male   
2      Married-civ-spouse     Prof-specialty      Husband  White    Male   
3      Married-civ-spouse  Machine-op-inspct      Husband  White    Male   
4      Married-civ-spouse  Machine-op-inspct      Husband  White    Male   
...                   ...                ...          ...    ...     ...   
27409  Married-civ-spouse       Tech-support         Wife  White  Female   
27410  Married-civ-spouse  Machine-op-inspct      Husband  White    Male   
27411             Widowed       Adm-clerical    Unmarried  White  Female   
27412       Never-married       Adm-clerical    Own-child  White    Male   
27413  Married-civ-spouse    Exec-managerial         Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country income  
0                 0             0              40  United-States   >50K  
1              7688             0              40  United-States   >50K  
2              3103             0              32  United-States   >50K  
3              6418             0              40  United-States   >50K  
4              3103             0              48  United-States   >50K  
...             ...           ...             ...            ...    ...  
27409             0             0              38  United-States  <=50K  
27410             0             0              40  United-States   >50K  
27411             0             0              40  United-States  <=50K  
27412             0             0              20  United-States  <=50K  
27413         15024             0              40  United-States   >50K  

[27414 rows x 15 columns]

In [4]:
data["income"].unique()

array(['>50K', '<=50K'], dtype=object)

In [5]:
data.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [6]:
data.describe()

age        fnlwgt  educational-num  capital-gain  \
count  27414.000000  2.741400e+04     27414.000000  27414.000000   
mean      40.001277  1.892254e+05        10.444627   1805.023492   
std       13.176862  1.047306e+05         2.620721   9848.645284   
min       17.000000  1.228500e+04         1.000000      0.000000   
25%       30.000000  1.180010e+05         9.000000      0.000000   
50%       39.000000  1.778335e+05        10.000000      0.000000   
75%       49.000000  2.360210e+05        13.000000      0.000000   
max       90.000000  1.484705e+06        16.000000  99999.000000   

       capital-loss  hours-per-week  
count  27414.000000    27414.000000  
mean     112.538229       41.618662  
std      458.418180       12.267420  
min        0.000000        1.000000  
25%        0.000000       40.000000  
50%        0.000000       40.000000  
75%        0.000000       48.000000  
max     4356.000000       99.000000

In [7]:
data.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'educational-num',
       'marital-status', 'occupation', 'relationship', 'race', 'gender',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [8]:
#checking unique values in a data
for i in data.columns:
    print(f"Unique values in column{i}:\n\n{data[i].unique()}\n")

Unique values in columnage:

[28 44 63 65 48 43 40 34 45 46 36 22 42 41 55 33 59 29 27 31 58 54 37 56
 39 51 50 52 47 24 64 53 35 32 30 68 57 66 49 38 61 73 26 23 25 62 90 60
 67 69 72 85 71 77 70 19 21 74 75 20 81 76 80 88 78 79 84 17 18 82 83 86
 87]

Unique values in columnworkclass:

['Local-gov' 'Private' 'Self-emp-not-inc' 'State-gov' 'Self-emp-inc' '?'
 'Federal-gov' 'Without-pay' 'Never-worked']

Unique values in columnfnlwgt:

[336951 160323 104626 ...  84661 310152 257302]

Unique values in columneducation:

['Assoc-acdm' 'Some-college' 'Prof-school' 'HS-grad' 'Masters' 'Doctorate'
 'Bachelors' 'Assoc-voc' '9th' '10th' '7th-8th' '11th' '5th-6th' '1st-4th'
 '12th' 'Preschool']

Unique values in columneducational-num:

[12 10 15  9 14 16 13 11  5  6  4  7  3  2  8  1]

Unique values in columnmarital-status:

['Married-civ-spouse' 'Never-married' 'Divorced' 'Separated'
 'Married-AF-spouse' 'Widowed' 'Married-spouse-absent']

Unique values in columnoccupation:

['Protective-serv'

In [9]:
import numpy as np
data_new=data.replace("?",np.nan)

In [10]:
data_new.isnull().sum()

age                   0
workclass          1283
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         1288
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      508
income                0
dtype: int64

In [11]:
data_new["workclass"].fillna(data_new["workclass"].mode()[0],inplace=True)
data_new["occupation"].fillna(data_new["occupation"].mode()[0],inplace=True)
data_new["native-country"].fillna(data_new["native-country"].mode()[0],inplace=True)

In [12]:
data_new.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [13]:
colname=[]
for x in data_new.columns:
    if data_new[x].dtypes=='object':
        colname.append(x)
colname

['workclass',
 'education',
 'marital-status',
 'occupation',
 'relationship',
 'race',
 'gender',
 'native-country',
 'income']

In [16]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for x in colname:
    data_new[x]=le.fit_transform(data_new[x])
    le_name_mapping = dict(zip(le.classes_,le.transform(le.classes_)))
    print('Feature',x)
    print('mapping',le_name_mapping)

Feature workclass
mapping {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7}
Feature education
mapping {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, 13: 13, 14: 14, 15: 15}
Feature marital-status
mapping {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6}
Feature occupation
mapping {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, 13: 13}
Feature relationship
mapping {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5}
Feature race
mapping {0: 0, 1: 1, 2: 2, 3: 3, 4: 4}
Feature gender
mapping {0: 0, 1: 1}
Feature native-country
mapping {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, 13: 13, 14: 14, 15: 15, 16: 16, 17: 17, 18: 18, 19: 19, 20: 20, 21: 21, 22: 22, 23: 23, 24: 24, 25: 25, 26: 26, 27: 27, 28: 28, 29: 29, 30: 30, 31: 31, 32: 32, 33: 33, 34: 34, 35: 35, 36: 36, 37: 37, 38: 38, 39: 39, 40: 40}
Feature income
mapping {0: 0, 1: 1}


In [17]:
data_new

age  workclass  fnlwgt  education  educational-num  marital-status  \
0       28          1  336951          7               12               2   
1       44          3  160323         15               10               2   
2       63          5  104626         14               15               2   
3       65          3  184454         11                9               2   
4       48          3  279724         11                9               2   
...    ...        ...     ...        ...              ...             ...   
27409   27          3  257302          7               12               2   
27410   40          3  154374         11                9               2   
27411   58          3  151910         11                9               6   
27412   22          3  201490         11                9               4   
27413   52          4  287927         11                9               2   

       occupation  relationship  race  gender  capital-gain  capital-loss  \
0              10             0     4       1             0             0   
1               6             0     2       1          7688             0   
2               9             0     4       1          3103             0   
3               6             0     4       1          6418             0   
4               6             0     4       1          3103             0   
...           ...           ...   ...     ...           ...           ...   
27409          12             5     4       0             0             0   
27410           6             0     4       1             0             0   
27411           0             4     4       0             0             0   
27412           0             3     4       1             0             0   
27413           3             5     4       0         15024             0   

       hours-per-week  native-country  income  
0                  40              38       1  
1                  40              38       1  
2                  32              38       1  
3                  40              38       1  
4                  48              38       1  
...               ...             ...     ...  
27409              38              38       0  
27410              40              38       1  
27411              40              38       0  
27412              20              38       0  
27413              40              38       1  

[27414 rows x 15 columns]

In [19]:
x=data_new.values[:, 0:-1]
y=data_new.values[:,-1] 

In [21]:
y

array([1, 1, 1, ..., 0, 0, 1], dtype=int64)

In [24]:
x.shape

(27414, 14)

In [25]:
y.shape


(27414,)

In [27]:
from sklearn.model_selection import train_test_split

In [30]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=10)

In [31]:
print("shape of x-train",x_train.shape)
print("shape of x-test",x_test.shape)
print("shape of y-train",y_train.shape)
print("shape of y-test",y_test.shape)

shape of x-train (19189, 14)
shape of x-test (8225, 14)
shape of y-train (19189,)
shape of y-test (8225,)


In [32]:
from sklearn .linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train,y_train)

LogisticRegression()

In [34]:
y_pred=classifier.predict(x_test)
print(y_pred)
print(list(zip(y_test,y_pred)))

[1 0 0 ... 0 1 0]
[(1, 1), (1, 0), (1, 0), (1, 0), (1, 1), (1, 0), (0, 0), (0, 0), (1, 1), (1, 1), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (1, 1), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (0, 0), (1, 0), (1, 0), (1, 0), (0, 0), (1, 0), (1, 0), (1, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (0, 1), (1, 0), (1, 0), (1, 1), (0, 0), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (1, 1), (1, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (1, 0), (0, 1), (0, 0), (1, 0), (1, 1), (1, 0), (1, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 0), (0, 0), (1, 1), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 0), (0, 0), (0, 0), (1, 0), (0, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0

In [37]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfm=confusion_matrix(y_test,y_pred)
print(cfm)
print("classification Report:")
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print("Accuracy of the model :",acc)

[[4396  311]
 [2371 1147]]
classification Report:
              precision    recall  f1-score   support

           0       0.65      0.93      0.77      4707
           1       0.79      0.33      0.46      3518

    accuracy                           0.67      8225
   macro avg       0.72      0.63      0.61      8225
weighted avg       0.71      0.67      0.64      8225

Accuracy of the model : 0.6739209726443769
